use_frameworks!

target 'GeoMagnetism_Example' do
  pod 'GeoMagnetism', :path => '../'

  target 'GeoMagnetism_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
